server:
  port: 9001
logging:
  config: classpath:logging-config.xml
spring:
#  sql:
#    init:
#      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
#      mode: always
#      mode: never
  profiles:
    active: mysql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
