server:
  port: 9100

logging:
  config: classpath:logging-config.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: root12345678
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot \u9ED8\u8BA4\u662F\u4E0D\u6CE8\u5165\u8FD9\u4E9B\u5C5E\u6027\u503C\u7684\uFF0C\u9700\u8981\u81EA\u5DF1\u7ED1\u5B9A
    #druid \u6570\u636E\u6E90\u4E13\u6709\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # \u6253\u5F00PSCache
    poolPreparedStatements: true
    #\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0Cstat:\u76D1\u63A7\u7EDF\u8BA1\u3001log4j\uFF1A\u65E5\u5FD7\u8BB0\u5F55\u3001wall\uFF1A\u9632\u5FA1sql\u6CE8\u5165
    #\u5982\u679C\u8FD0\u884C\u65F6\u62A5\u9519  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #\u5219\u5BFC\u5165 log4j \u4F9D\u8D56\u5373\u53EF\uFF0CMaven \u5730\u5740\uFF1A https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,slf4j,config
    #\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
    maxPoolPreparedStatementPerConnectionSize: 20
    #\u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
    useGlobalDataSourceStat: true
    #\u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



